export const IS_AUTHENTICATED = false;
export const AUTHENTICATE = "AUTHENTICATE";
export const WATCHLIST_REFRESH = "WATCHLIST_REFRESH";
export const WATCHLIST_UPDATE_SYMBOL = "WATCHLIST_UPDATE_SYMBOL";
export const WATCHLIST_SET_SYMBOL = "WATCHLIST_SET_SYMBOL";
export const WATCHLIST_SET_DATA = "WATCHLIST_SET_DATA";
export const WATCHLIST_UPDATE_DATA = "WATCHLIST_UPDATE_DATA";
